version: '3.8'

services:
  backend:
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  nginx:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend