# Generated by Django 5.2.1 on 2025-06-18 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='授業タイトル')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日'), (7, '日曜日')], null=True, verbose_name='曜日')),
                ('period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='時限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='課題タイトル')),
                ('content', models.TextField(blank=True, null=True, verbose_name='課題詳細')),
                ('url', models.URLField(max_length=512, verbose_name='課題URL')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='提出期限')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='提出済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scraping.course')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('user', 'url')},
            },
        ),
    ]
