# Generated by Django 5.2.1 on 2025-06-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='課題URL'),
        ),
    ]
