# Generated by Django 5.2.1 on 2025-06-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_assignment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プラットフォーム'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始日時'),
        ),
    ]
