# Generated by Django 5.2.1 on 2025-06-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scraping', '0003_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('user', 'url')},
        ),
    ]
