# Generated by Django 5.2.1 on 2025-06-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_assignment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='url',
            field=models.URLField(max_length=512, verbose_name='課題URL'),
        ),
    ]
