# Generated by Django 5.2.1 on 2025-06-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_alter_assignment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='提出済み'),
        ),
    ]
